name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: publish_nyxx_base
        uses: abitofevrything/publish-mason-brick@1.0.2
        with:
          path: nyxx_base
          email: ${{ secrets.BRICKHUB_EMAIL }}
          password: ${{ secrets.BRICKHUB_PASSWORD }}

      - name: publish_nyxx_commands
        uses: abitofevrything/publish-mason-brick@1.0.2
        with:
          path: nyxx_commands
          email: ${{ secrets.BRICKHUB_EMAIL }}
          password: ${{ secrets.BRICKHUB_PASSWORD }}

      - name: publish_nyxx_full
        uses: abitofevrything/publish-mason-brick@1.0.2
        with:
          path: nyxx_full
          email: ${{ secrets.BRICKHUB_EMAIL }}
          password: ${{ secrets.BRICKHUB_PASSWORD }}

      - name: publish_nyxx_commands_command
        uses: abitofevrything/publish-mason-brick@1.0.2
        with:
          path: nyxx_commands_command
          email: ${{ secrets.BRICKHUB_EMAIL }}
          password: ${{ secrets.BRICKHUB_PASSWORD }}
